# Generated by Django 3.1.2 on 2022-05-08 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='articles.article')),
            ],
        ),
    ]
