# Generated by Django 3.1.2 on 2022-05-08 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='articles',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.CreateModel(
            name='ArticleChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heading', to='articles.article')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heading', to='articles.chapter')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='articles',
            field=models.ManyToManyField(related_name='topic', through='articles.ArticleChapter', to='articles.Article'),
        ),
    ]
